### base config file
data:
    name: 'patches_dataset'
    dataset: 'hpatches'  # 'hpatches' 'coco'
    alteration: 'all'  # 'i' 'v' 'all'
    cache_in_memory: false
    shuffle: true
    preprocessing:
        resize: [480, 640]  # False for coco
    ### augmentation
    augmentation:
        photometric:
            enable: True
            primitives: [
                'additive_gaussian_noise'
            ]
            params:
                additive_gaussian_noise: {stddev_range: [5, 5]} # [0, 10]
training:
    val_batches: 2 # batches of validation, batch = 1
    reproduce: true

model:
    name: 'classical_detectors_descriptors'
    filter: # 'bilateral'
    filter: 'bilateral'
    filter_d: 11
    method: 'sift'  # 'sift'
    batch_size: 1  # unused
    nms: 4
    top_k: 1000  ## not useful
eval_iter: 600
seed: 1

